# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.degree = QtWidgets.QLineEdit(Form)
        self.degree.setObjectName("degree")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.degree)
        self.description = QtWidgets.QTextEdit(Form)
        self.description.setObjectName("description")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.description)
        self.state_0 = QtWidgets.QRadioButton(Form)
        self.state_0.setObjectName("state_0")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.state_0)
        self.state_1 = QtWidgets.QRadioButton(Form)
        self.state_1.setObjectName("state_1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.state_1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.price = QtWidgets.QSpinBox(Form)
        self.price.setMaximum(1000000000)
        self.price.setObjectName("price")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.price)
        self.size = QtWidgets.QSpinBox(Form)
        self.size.setMaximum(1000000000)
        self.size.setObjectName("size")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.size)
        self.verticalLayout.addLayout(self.formLayout)
        self.error = QtWidgets.QLabel(Form)
        self.error.setStyleSheet("color: #f00;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.verticalLayout.addWidget(self.error)
        self.add_edit_btn = QtWidgets.QPushButton(Form)
        self.add_edit_btn.setObjectName("add_edit_btn")
        self.verticalLayout.addWidget(self.add_edit_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление нового кофе"))
        self.label.setText(_translate("Form", "Название сорта"))
        self.label_2.setText(_translate("Form", "Степень обжарки"))
        self.label_3.setText(_translate("Form", "Форма"))
        self.label_4.setText(_translate("Form", "Описание вкуса"))
        self.state_0.setText(_translate("Form", "Молотый"))
        self.state_1.setText(_translate("Form", "В зёрнах"))
        self.label_5.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Объем упаковки"))
        self.add_edit_btn.setText(_translate("Form", "Доабавить"))
